pipeline {
    agent any
    stages {
        stage('prepare') {
            steps {
                sh 'echo "Preparing Build Job"'
            } 
        stage('build') {
            steps {
                sh 'javac -d . src/*.java'
                sh 'echo Main-Class: Rectangulator > MANIFEST.MF'
                sh 'jar -cvmf MANIFEST.MF rectangle.jar *.class'
            }
        }
        stage('run') {
            steps {
                sh 'java -jar rectangle.jar 7 9'
            }
        }
        stage('archive') {
            steps {
                sh 'echo "Archiving Ouptput Files"'
            }
        }
    }
}
